[project]
name = "graph1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipython>=9.7.0",
    "jupyter>=1.1.1",
    "langgraph>=1.0.3",
]
